version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue",
    "angularjs"
  ]
  environment = [
    "nodejs",
    "mongo",
    "jest",
    "jquery",
    "vitest"
  ]